# RUNCARDS USED ONLY FOR PULLING DATA WITH FINALISE.PY 
dictCard = {
    # 'RRa.run':'DM_RRa',
    # 'RRb.run':'DM_RRb',
    # 'RV.run':'DM_RV',
    # 'VV.run':'DM_VV',
    # 'R.run':'DM_R',
    # 'V.run':'DM_V',
    # 'LO.run':'DM_LO',
    # 'Ra_Wm.run':'WM_VAL_Ra',
    # 'Rb_Wm.run':'WM_VAL_Rb',
    # 'V_Wm.run':'WM_VAL_V',
    # 'Ra_Wp.run':'WP_VAL_Ra',
    # 'Rb_Wp.run':'WP_VAL_Rb',
    # 'V_Wp.run':'WP_VAL_V',
    # 'RRa_fix_scale.run':'RRa_DM_FIX',
    # 'RRb_fix_scale.run':'RRb_DM_FIX',
    # 'RV_fix_scale.run':'RV_DM_FIX',
    # 'VV_fix_scale.run':'VV_DM_FIX',
    # 'R_fix_scale.run':'R_DM_FIX',
    # 'V_fix_scale.run':'V_DM_FIX',
    # 'LO_fix_scale.run':'LO_DM_FIX',
    # 'RRa_fix_scale_Janfix.run': 'RRa_DM_JAN',
    # 'RRb_fix_scale_Janfix.run': 'RRb_DM_JAN',

    # 'ubgRa.run':'Ra',
    # 'ubgRb.run':'Rb',
    # 'ubgV.run':'V',
    # 'dbgRa.run':'Ra',
    # 'dbgRb.run':'Rb',
    # 'dbgV.run':'V',
    # 'QbgRa.run':'Ra',
    # 'QbgRb.run':'Rb',
    # 'QbgV.run':'V',

    }
