#!/bin/bash

# Bash wrapper around main.py to allow for multiple runcards
# Accepts the same syntax as ./main.py because it's basically a wrapper around it

SCRIPT_NAME="./main.py"

mode=$1
shift
arguments_raw=$@
options=-${arguments_raw#*-}
runcards=${arguments_raw%$options*}

# Debug
# SCRIPT_NAME="echo ./main.py "
# echo mode: $mode
# echo runcards: $runcards
# echo options: $options

if [ -z "$runcards" ]
then
    $SCRIPT_NAME $mode $@
fi

for runcard in $runcards
do
    $SCRIPT_NAME $mode $runcard $options
done
